export const VIDEO_SECTIONS = [
  {
    header: 'Introduction',
    desc: 'Know about the Reporter, what it is, why was it built and by who.',
    sec: 3,
  },
  {
    header: 'Getting Started',
    desc: 'Know more about what how to use the buttons on the toolbar.',
    sec: 33,
  },
  {
    header: 'Search',
    desc: 'Search entities by typing their names.',
    sec: 117,
  },
  {
    header: 'Indented List',
    desc: 'View the data in a hierarchical format.',
    sec: 207,
  },
  {
    header: 'Report Generator',
    desc: 'The Reporter computes various statistics from the data - which is downloadable.',
    sec: 232,
  },
  {
    header: 'Debug Log',
    desc: 'The Log lists warnings and errors that occurred during data parsing and visualization creation',
    sec: 247,
  },
  {
    header: 'Export',
    desc: 'The menu lists the formats that can be exported through the reporter.',
    sec: 270,
  },
  {
    header: 'Tree Visualization',
    desc: 'See how to explore the tree visualization.',
    sec: 304,
  },
  {
    header: 'Graph Functions',
    desc: 'See how you can sort, size and filter different nodes.',
    sec: 400,
  },
  {
    header: 'Graph Controls',
    desc: 'Constomize the visualization on the fly.',
    sec: 480,
  },
  {
    header: 'Compare',
    desc: 'Compare your data to that of the master tables.',
    sec: 540,
  },
  {
    header: 'Playground',
    desc: 'Play with the visualization and upload your own data.',
    sec: 669,
  },
  {
    header: 'Docs',
    desc: 'Take a look at the Reporter Documentation.',
    sec: 796,
  },
];

export const CONTRIBUTORS = [
  {
    img: 'contributors/paul.jpg',
    name: 'Hrishikesh Paul',
    desc: 'Software Engineer Team Lead',
    mail: 'hrpaul@iu.edu',
    link: 'https://hrishikeshpaul.github.io',
    linkedin: 'https://www.linkedin.com/in/hrishikeshpaul/',
    github: 'https://github.com/hrishikeshpaul',
  },
  {
    img: 'contributors/katy.png',
    name: 'Katy Börner',
    desc: 'Director & Researcher',
    mail: 'katy@iu.edu',
    link: 'https://info.sice.indiana.edu/~katy/',
    linkedin: 'https://www.linkedin.com/in/katy-borner-a03837/',
    github: '',
  },
  {
    img: 'contributors/bruce.jpg',
    name: 'Bruce W Herr II',
    desc: 'Senior System Architect',
    mail: 'bherr@iu.edu',
    link: 'https://cns.iu.edu/current_team/bio/bruce-herr.html',
    linkedin: 'https://www.linkedin.com/in/bruceherr/',
    github: 'https://github.com/bherr2',
  },
  {
    img: 'contributors/ellen.jpeg',
    name: 'Ellen M Quardokus',
    desc: 'Senior Research Analyst',
    mail: 'ellenmq@iu.edu',
    link: 'https://cns.iu.edu/current_team/bio/ellen-quardokus.html',
    linkedin: '',
    github: '',
  },
  {
    img: 'contributors/ajay.jpeg',
    name: 'Sai Ajay Vutukuri',
    desc: 'Software Developer',
    mail: 'svutuku@iu.edu',
    link: 'https://github.com/vutukuriajay2241',
    linkedin: 'https://in.linkedin.com/in/ajay-vutukuri-38824ba8',
    github: '',
  },
  {
    img: 'contributors/mac.jpeg',
    name: 'Mac Vogelsang',
    desc: 'Software Developer',
    mail: 'madvogel@iu.edu',
    link: 'https://github.com/macvogelsang',
    linkedin: 'https://www.linkedin.com/in/mac-vogelsang',
    github: '',
  },
  {
    img: 'contributors/nikhil.jpeg',
    name: 'Nikhil Mahadevaswamy',
    desc: 'Angular Developer',
    mail: 'nmahade@iu.edu',
    link: 'https://github.com/Nikhil-lab',
    linkedin: 'https://www.linkedin.com/in/nikhilm2395',
    github: '',
  },
  {
    img: 'contributors/pramod.png',
    name: 'Pramod Bhakta',
    desc: 'Angular Developer',
    mail: 'pnbhakta@iu.edu',
    link: 'https://github.com/pbrm4',
    github: '',
  },
];
