name: Find app and storybook directories
description: List the names of directories in dist/apps/ and dist/storybook/

outputs:
  apps:
    description: Comma seperated names of app directories
    value: ${{ steps.collect.outputs.apps }}
  storybooks:
    description: Comma seperated names of storybook directories
    value: ${{ steps.collect.outputs.storybooks }}

runs:
  using: composite
  steps:
    - name: Collect directories
      id: collect
      shell: bash
      run: |
        apps=`find ./dist/apps/ -maxdepth 1 -mindepth 1 -type d -printf '%f,'`
        storybooks=`find ./dist/storybook/ -maxdepth 1 -mindepth 1 -type d -printf '%f,'`
        echo "apps=${apps::-1}" >> $GITHUB_OUTPUT
        echo "storybooks=${storybooks::-1}" >> $GITHUB_OUTPUT
